Insert into users(userfname, userlname, username, useremail, userpassword, userphoto, userdob, useraddress, usercountry, companyname, companylogo, companydescription, nbshareordinary, sharevalueordinary, descordinary, additionalordinary, nbsharepreferencial, sharevaluepreferencial, descpreferencial, additionalpreferencial, nbsharenonvoting, sharevaluenonvoting, descnonvoting, additionalnonvoting, nbshareredeemable, sharevalueredeemable, descredeemable, additionalredeemable, userassets, isadmin, "validatedUser") values 
('admin', 'admin', 'admin', 'admin@example.com', 'Testons123', 'images/avatar.png', '12/05/1988', 'Admin Street', 'Germany', 'admin', 'images/78899.jpg', 'admin', 0, 0, 'admin', 'admin', 0, 0, 'admin', 'admin', 0, 0, 'admin', 'admin', 0, 0, 'admin', 'admin', 0, 't', 't');

Insert into users(userfname, userlname, username, useremail, userpassword, userphoto, userdob, useraddress, usercountry, companyname, companylogo, companydescription, nbshareordinary, sharevalueordinary, descordinary, additionalordinary, nbsharepreferencial, sharevaluepreferencial, descpreferencial, additionalpreferencial, nbsharenonvoting, sharevaluenonvoting, descnonvoting, additionalnonvoting, nbshareredeemable, sharevalueredeemable, descredeemable, additionalredeemable, userassets, isadmin, "validatedUser") values 
('John', 'Doe', 'johndoe', 'johndoe@example.com', 'Testons123', 'images/avatar.png', '05/02/1982', '123 Abc Street', 'Australia', 'Doe Ltd', 'images/78899.jpg', 'Praesent molestie leo purus, non tincidunt libero vehicula efficitur. Nulla facilisi. Integer imperdiet enim vestibulum orci maximus, vitae dignissim ante ornare.',4582, 0.12, 'Mei possit dignissim et. Ad semper adipiscing duo. Inani deserunt urbanitas pri ne, ex mei velit hendrerit neglegentur, nemore percipit ei nam. Nostro habemus has ea.', 'one, two, three, four',85202, 5.1, 'Vis ad purto appetere, fastidii definitiones ut duo, ne saepe salutatus patrioque nec. Te movet sonet graeci usu, ea sint clita vim.', 'one, two, three, four',8961, 0.04, 'Tractatos conclusionemque mel no, nam stet nibh malorum et. Id eos quem facer offendit, est ut odio debitis. Postulant evertitur consequuntur has at.', 'one, two, three, four',1523, 1.13, 'Et has animal veritus. Vix ut timeam eleifend pericula. Ius et equidem adipisci, animal repudiandae nec id.', 'one, two, three, four', 6520, 't', 't');

Insert into users(userfname, userlname, username, useremail, userpassword, userphoto, userdob, useraddress, usercountry, companyname, companylogo, companydescription, nbshareordinary, sharevalueordinary, descordinary, additionalordinary, nbsharepreferencial, sharevaluepreferencial, descpreferencial, additionalpreferencial, nbsharenonvoting, sharevaluenonvoting, descnonvoting, additionalnonvoting, nbshareredeemable, sharevalueredeemable, descredeemable, additionalredeemable, userassets, isadmin, "validatedUser") values 
('Sarah', 'Stewart', 'sarahstewart', 'sarahstewart@example.com', 'Testons123', 'images/avatar.png', '03/10/1985', '456 def Street', 'Spain', 'Smoke Ltd', 'images/78899.jpg', 'Nullam tincidunt diam a imperdiet iaculis. Quisque ac maximus dui. Praesent molestie leo purus, non tincidunt libero vehicula efficitur. Nulla facilisi. Integer imperdiet enim vestibulum orci maximus, vitae dignissim ante ornare.',1541, 0.02, 'Ad semper adipiscing duo. Inani deserunt urbanitas pri ne, ex mei velit hendrerit neglegentur, nemore percipit ei nam. Nostro habemus has ea.', 'one, two, three, four',4852, 0.58, 'His id argumentum dissentias, nulla molestie scriptorem cu vis. Vis ad purto appetere, fastidii definitiones ut duo, ne saepe salutatus patrioque nec. Te movet sonet graeci usu, ea sint clita vim.', 'one, two, three, four',4585, 0.12, 'pri luptatum iracundia ne. Tractatos conclusionemque mel no, nam stet nibh malorum et. Id eos quem facer offendit, est ut odio debitis. Postulant evertitur consequuntur has at.', 'one, two, three, four',63154, 1.08, 'Mea no dolore invenire, et eum vocibus detracto inimicus. Et has animal veritus. Vix ut timeam eleifend pericula. Ius et equidem adipisci, animal repudiandae nec id.', 'one, two, three, four', 4850, 't', 't');

Insert into users(userfname, userlname, username, useremail, userpassword, userphoto, userdob, useraddress, usercountry, companyname, companylogo, companydescription, nbshareordinary, sharevalueordinary, descordinary, additionalordinary, nbsharepreferencial, sharevaluepreferencial, descpreferencial, additionalpreferencial, nbsharenonvoting, sharevaluenonvoting, descnonvoting, additionalnonvoting, nbshareredeemable, sharevalueredeemable, descredeemable, additionalredeemable, userassets, isadmin, "validatedUser") values 
('Jane', 'Smith', 'janeSmith', 'janeSmith@example.com', 'Testons123', 'images/avatar.png', '03/02/1980', '789 ghi Street', 'Haiti', 'Rand Tech', 'images/78899.jpg', 'Gravida at mauris a facilisis. Nullam tincidunt diam a imperdiet iaculis. Quisque ac maximus dui. Praesent molestie leo purus, non tincidunt libero vehicula efficitur. Nulla facilisi. Integer imperdiet enim vestibulum orci maximus, vitae dignissim ante ornare.',1541, 0.02, 'Dignissim et. Ad semper adipiscing duo. Inani deserunt urbanitas pri ne, ex mei velit hendrerit neglegentur, nemore percipit ei nam. ', 'one, two, three, four',4852, 0.58, 'Te movet sonet graeci usu, ea sint clita vim.', 'one, two, three, four',4585, 0.12, 'At nam falli ludus dignissiml no, nam stet nibh malorum et. Id eos quem facer offendit, est ut odio debitis. Postulant evertitur consequuntur has at.', 'one, two, three, four',63154, 1.08, 'Invenire, et eum vocibus detracto inimicus. Et has animal veritus. Vix ut timeam eleifend pericula. Ius et equidem adipisci, animal repudiandae nec id.', 'one, two, three, four', 4850, 'f', 'f');


